# -*- coding: utf-8 -*-
"""Iris Flower Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QacyfbHUDGcc-pL5sdBTJrfW8cP0DPQI

#Load the Dataset
"""

from sklearn.datasets import load_iris
import pandas as pd

# Load the dataset
iris = load_iris()

# Create a DataFrame for better visualization
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = iris.target

# Map species to their names
df['species'] = df['species'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})
print(df.head())

"""#Split the Dataset"""

from sklearn.model_selection import train_test_split

X = iris.data  # Features
y = iris.target  # Labels (species)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""#Train the Model"""

from sklearn.ensemble import RandomForestClassifier

# Initialize the model
model = RandomForestClassifier(random_state=42)

# Train the model
model.fit(X_train, y_train)

"""#Evaluate the Model"""

from sklearn.metrics import accuracy_score, classification_report

# Predict the species for test data
y_pred = model.predict(X_test)

# Evaluate the performance
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=iris.target_names))

"""#Test the Model with New Data"""

# Example measurements: [sepal length, sepal width, petal length, petal width]
new_flower = [[5.1, 3.5, 1.4, 0.2]]
prediction = model.predict(new_flower)

# Map the prediction to species name
print("Predicted Species:", iris.target_names[prediction[0]])

"""#Visualization"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.pairplot(df, hue='species', markers=["o", "s", "D"])
plt.show()